In [60]:
import numpy as np
from sklearn.datasets import load_iris
import tensorflow as tf

In [61]:
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [62]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [63]:
X = iris.data
y = iris.target

In [64]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#### One hot encode the target

In [65]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
y = to_categorical(y)

In [66]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [67]:
y.shape

(150, 3)

In [68]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [69]:
print('X_train',X_train[:5])
print('X_test',X_test[:5])

X_train [[5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]]
X_test [[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]]


In [70]:
print('y_train',y_train[:5])
print('y_test',y_test[:5])

y_train [[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
y_test [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [71]:
from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()
scaled_X_train = scaler_object.fit_transform(X_train)

In [72]:
scaled_X_test = scaler_object.fit_transform(X_test)

In [73]:
scaled_X_train[:5]

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667]])

### Build the network

In [74]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense



In [75]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer = 'adam',metrics=['accuracy'])

In [76]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [77]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 0s - loss: 1.0655 - accuracy: 0.3400
Epoch 2/150
4/4 - 0s - loss: 1.0593 - accuracy: 0.3400
Epoch 3/150
4/4 - 0s - loss: 1.0540 - accuracy: 0.3400
Epoch 4/150
4/4 - 0s - loss: 1.0488 - accuracy: 0.3500
Epoch 5/150
4/4 - 0s - loss: 1.0440 - accuracy: 0.3500
Epoch 6/150
4/4 - 0s - loss: 1.0398 - accuracy: 0.3600
Epoch 7/150
4/4 - 0s - loss: 1.0360 - accuracy: 0.3600
Epoch 8/150
4/4 - 0s - loss: 1.0312 - accuracy: 0.3600
Epoch 9/150
4/4 - 0s - loss: 1.0267 - accuracy: 0.3600
Epoch 10/150
4/4 - 0s - loss: 1.0224 - accuracy: 0.3800
Epoch 11/150
4/4 - 0s - loss: 1.0180 - accuracy: 0.3800
Epoch 12/150
4/4 - 0s - loss: 1.0132 - accuracy: 0.3800
Epoch 13/150
4/4 - 0s - loss: 1.0079 - accuracy: 0.4000
Epoch 14/150
4/4 - 0s - loss: 1.0027 - accuracy: 0.4400
Epoch 15/150
4/4 - 0s - loss: 0.9975 - accuracy: 0.5000
Epoch 16/150
4/4 - 0s - loss: 0.9923 - accuracy: 0.5500
Epoch 17/150
4/4 - 0s - loss: 0.9869 - accuracy: 0.5800
Epoch 18/150
4/4 - 0s - loss: 0.9817 - accuracy: 0.5900
E

In [83]:
model.predict(scaled_X_test)

array([[2.39009019e-02, 6.63848162e-01, 3.12250882e-01],
       [9.46881533e-01, 5.18975668e-02, 1.22089207e-03],
       [9.56062722e-05, 7.34721497e-02, 9.26432252e-01],
       [1.32450489e-02, 5.27690947e-01, 4.59064037e-01],
       [8.06887727e-03, 5.20121932e-01, 4.71809208e-01],
       [9.17005420e-01, 8.01129416e-02, 2.88168085e-03],
       [6.46846369e-02, 7.00317085e-01, 2.34998330e-01],
       [4.17624920e-04, 1.18675224e-01, 8.80907118e-01],
       [6.49844855e-03, 4.21764582e-01, 5.71736991e-01],
       [4.00021747e-02, 6.92917049e-01, 2.67080843e-01],
       [1.71676930e-03, 2.42996529e-01, 7.55286753e-01],
       [9.48528767e-01, 4.87808809e-02, 2.69033783e-03],
       [9.56739187e-01, 4.20341790e-02, 1.22658547e-03],
       [9.51075733e-01, 4.65851389e-02, 2.33907462e-03],
       [9.72077966e-01, 2.70415470e-02, 8.80426029e-04],
       [1.16275242e-02, 5.44826806e-01, 4.43545640e-01],
       [5.30834310e-04, 1.17908634e-01, 8.81560504e-01],
       [4.72145043e-02, 7.07327

In [88]:
np.argmax(model.predict(scaled_X_test), axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [89]:
predictions = np.argmax(model.predict(scaled_X_test),axis=1)

In [91]:
y_test_arg = y_test.argmax(axis=1)

In [93]:
y_test[:5]

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [94]:
y_test_arg[:5]

array([1, 0, 2, 1, 1], dtype=int64)

In [96]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

print(confusion_matrix(y_test_arg,predictions))

[[19  0  0]
 [ 0 14  1]
 [ 0  0 16]]


In [97]:
print(classification_report(y_test_arg,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [ ]:
! git add Iris_deepLearning.ipynb
! git commit -m "15:53/31-01-2022"
! git push origin main