In [2]:
import pandas as pd


In [3]:
npr = pd.read_csv('npr.csv')

In [4]:
npr

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [18]:
npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_df = 0.9,min_df=2,stop_words='english') # max_df = Discard words that shows up in 90% of the documnet
# min_df = word that show up minimum number of time. Here it should appear 2 times in a document

In [24]:
# Document term matrix
### A document-term matrix is a mathematical matrix that describes the frequency of terms that occur in a collection of documents.
dtm = cv.fit_transform(npr['Article'])
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [25]:
from sklearn.decomposition import LatentDirichletAllocation

LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [26]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [27]:
#Grab the highest probability word per topic

In [34]:
# Grab the vocab of words

print(len(cv.get_feature_names()))

type(cv.get_feature_names())

cv.get_feature_names()[50000]

54777


'transcribe'

In [36]:
import random 

random_word_id = random.randint(0,54777)

cv.get_feature_names()[10]

'01'

In [40]:
# Grab the topics

print(len(LDA.components_))
print(type(LDA.components_))


7
<class 'numpy.ndarray'>


In [41]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [42]:
single_topic = LDA.components_[0]
single_topic.argsort() # return index position that would sort this array

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [45]:
### Arg sort example
import numpy as np

arr = np.array([100,200,1])

arr.argsort()

array([2, 0, 1], dtype=int64)

In [46]:
# Argsort returns back index position sorted from least to greatest
# Top 10 values (10 Greatest values)
# Last 10 values of Argsort()
single_topic.argsort()[-10:] # grab the last 10 values of .argsort()

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [48]:
top_ten_words = single_topic.argsort()[-10:]


In [50]:
for index in top_ten_words:
    print(cv.get_feature_names()[index])

C:\Users\manda\anaconda3\envs\nlpenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


new
percent
government
company
million
care
people
health
said
says


In [52]:
### Grab the highest probability word per topic

for i,topic in enumerate(LDA.components_):
    print(f"The top 15 words for topic #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

The top 15 words for topic #0


C:\Users\manda\anaconda3\envs\nlpenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




The top 15 words for topic #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




The top 15 words for topic #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




The top 15 words for topic #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




The top 15 words for topic #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




The top 15 words for topic #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', '

In [58]:
# Attach topic number to the original articles

topic_results = LDA.transform(dtm)


In [60]:
topic_results.shape

(11992, 7)

In [61]:
topic_results[0].argmax()

1

In [63]:
npr['Topic'] = topic_results.argmax(axis=1)

npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]

In [ ]:
! git add Latent_Dirichlet_Allocation.ipynb
! git commit -m "15:38/30-01-2022"
! git push origin main